### ISSUE TITLE
Timeout for Prelude (on IPFS)

### ISSUE THREAD

**Issue by vsund** [dhall-lang/dhall-text#11]
Hey,

I'd like to play a little bit around with this, but get a timeout from IPFS. I think this is related to the switch from IPFS to GitHub for Prelude (as @Gabriel439 said in https://github.com/dhall-lang/dhall-text/issues/8#issuecomment-398095124).

I guess this needs a little update due to the IPFS->GitHub switch? :)

---
For reference the error I'm getting:
```
$ dhall-to-text <<< './make-items ./people'
dhall-to-text: 
↳ ./make-items
  ↳ https://ipfs.io/ipfs/Qmbh2ifwcpX9a384vJMehySbV7rdvYhzVbL5ySs84k8BgY/Prelude/List/map
HttpExceptionRequest Request {
  host                 = "ipfs.io"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/ipfs/Qmbh2ifwcpX9a384vJMehySbV7rdvYhzVbL5ySs84k8BgY/Prelude/List/map"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ResponseTimeout
```

```
$ dhall-to-text version
1.0.11
```

**Comment by vsund** [comment]
Just noticed that I copied the examples from the readme to blindly. Fixed it with changing the Prelude links manually.

I'll add this as a PR after playing around some more.

---
`https://ipfs.io/ipfs/Qmbh2ifwcpX9a384vJMehySbV7rdvYhzVbL5ySs84k8BgY/Prelude/List/map`
to
`https://raw.githubusercontent.com/dhall-lang/Prelude/master/List/map`

`https://ipfs.io/ipfs/Qmbh2ifwcpX9a384vJMehySbV7rdvYhzVbL5ySs84k8BgY/Prelude/Text/concat`
to
`https://raw.githubusercontent.com/dhall-lang/Prelude/master/Text/concat`

**Comment by vsund** [comment]
Also seems like there was a change on `Integer`/`Natural` (found this while searching in some other issues).
The example from the readme doesn't work as is (independently from the IPFS/GitHub thing).

I had to prefix the numbers in `people` with a `+`. I guess one also could change the type to `Natural` (if you consider `upvotes` to be positive, from the wording it seems that there are no downvotes intended :D).

**Comment by vsund** [comment]
I added a PR for these things: https://github.com/dhall-lang/dhall-text/pull/12

**Comment by vsund** [comment]
Thanks for the quick response, going to close this now.

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by vsund** [comment]
After playing a little bit more with it, shouldn't the links be `http://prelude.dhall-lang.org/List/map` and `http://prelude.dhall-lang.org/Text/concat`? From other appearances of Prelude it seems like these are the canonical ones (and kinda makes sense to use a self-controlled link if you ever should come across moving it again).

**Comment by Gabriel439** [comment]
@vsund: Yeah, those would be the simpler URLS to use.  Another option is to keep the longer URLs but pin them to a specific revision so that they are future-proof

**Comment by vsund** [comment]
Just thought it might be better to use the canonical ones, but I leave this up to you :)
